language: c++

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang

git:
  depth: 1

services:
  # Virtual X is needed for analyzer waveform tests
  - xvfb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libavformat-dev
      - libchromaprint-dev
      - libfaad-dev
      - libflac-dev
      - libid3tag0-dev
      - liblilv-dev
      - libmad0-dev
      - libmodplug-dev
      - libmp3lame-dev
      - libmp4v2-dev
      - libopus-dev
      - libopusfile-dev
      - libportmidi-dev
      - libprotobuf-dev
      - libqt5opengl5-dev
      - libqt5sql5-sqlite
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - librubberband-dev
      - libshout3-dev
      - libsndfile1-dev
      - libsoundtouch-dev
      - libsqlite3-dev
      - libtag1-dev
      - libupower-glib-dev
      - libusb-1.0-0-dev
      - libwavpack-dev
      - portaudio19-dev
      - protobuf-compiler
      - qt5-default
      - qtscript5-dev
      - qt5keychain-dev
      - cmake
  homebrew:
    update: true
    packages:
      - chromaprint
      - faad2
      - ffmpeg
      - flac
      - lame
      - libsndfile
      - libogg
      - libvorbis
      - libshout
      - libmodplug
      - libid3tag
      - libmad
      - lilv
      - mp4v2
      - opusfile
      - portaudio
      - portmidi
      - protobuf
      - qt5
      - rubberband
      - cmake
      - sound-touch
      - taglib
      - wavpack

before_install:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export CMAKE_BUILD_PARALLEL_LEVEL="$(nproc)";
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export CMAKE_BUILD_PARALLEL_LEVEL="$(sysctl -n hw.ncpu)";
    fi

install:
  # Build flags common to OS X and Linux.
  # Parallel builds are important for avoiding OSX build timeouts.
  # We turn off verbose output to avoid going over the 4MB output limit.
  # TODO(2019-07-21): Add "FFMPEG_ENABLED=1" if FFmpeg 4.x becomes available in Ubuntu
  - export COMMON_FLAGS="
      -DMAD_ENABLED=ON \
      -DFAAD_ENABLED=ON \
      -DOPUS_ENABLED=ON
      -DMODPLUG_ENABLED=ON \
      -DWAVPACK_ENABLED=ON \
      -DHSS1394_ENABLED=OFF \
      "

  # Ubuntu Xenial build prerequisites
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export EXTRA_FLAGS="-DLOCALECOMPARE_ENABLED=ON";
    fi

  # NOTE(rryan): 2016-11-15 we are experiencing Travis timeouts for the OSX
  # build.  Turning off optimizations to see if that speeds up compile times.
  # TODO(rryan): localecompare doesn't work on Travis with qt5 for some reason.
  # TODO(2019-07-21): Move "ffmpeg=1" into COMMON_FLAGS if FFmpeg 4.x becomes available in Ubuntu
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export EXTRA_FLAGS="-DLOCALECOMPARE_ENABLED=OFF -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/";
      export PATH="/usr/local/opt/ccache/bin:$PATH";
    fi

  - mkdir cmake_build
  - cd cmake_build
  - cmake $COMMON_FLAGS $EXTRA_FLAGS ..
  - cmake --build .
  - sudo cmake --build . --target install

before_script:
  # Virtual X (Xvfb) is needed for analyzer waveform tests
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export DISPLAY=:99.0;
    fi
  # Build tests
  - cmake --build . --target mixxx-test

script:
  - export GTEST_COLOR=1 CTEST_OUTPUT_ON_FAILURE=1
  # Run tests
  - cmake --build . --target test
  # Run benchmarks
  - cmake --build . --target benchmark

notifications:
  webhooks:
    - https://mixxx.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=$ZULIP_API_KEY
